# Targets branching
parallel: FALSE

# Scope
single_well: FALSE
single_well_site: 1

# Testing and Resampling
initial_prop: 0.9
cv_initial: 0.5
cv_assess: 0.125
cv_skip: 0.125
cv_lag: 365, 52

# Parallel
allow_par: TRUE
cores: 30

# Tuning
hyppar_combinations: 5
hyppar_levels: 5
