# Targets branching
parallel: FALSE

# Scope
single_well: FALSE
single_well_site: 1

# Testing and Resampling
initial_prop: 0.9
cv_initial: 0.5
cv_assess: 24 months
cv_skip: 12 months
cv_lag: 365, 52
cv_slice_max: 4
reg_cv_folds: 5
repeats: 2

# Parallel
allow_par: TRUE
cores: 30

# Tuning
hyppar_combinations: 1
hyppar_levels: 1
