# Targets branching
parallel: FALSE

# Scope
single_well: TRUE
single_well_site: 1

# Testing and Resampling
initial_prop: 0.9
cv_initial: 2000
cv_assess: 600
cv_skip: 600
cv_lag: 365

# Parallel
allow_par: TRUE
cores: 9

# Tuning
hyppar_combinations: 12
